version: '3'
services:
  db:
    image: "postgres:12"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: crud

  db_test:
    image: "postgres:12"
    volumes:
      - ./db_data:/var/lib/postgresql/data_test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: crud_test

volumes:
  db_data: