spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    password: 3441
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
org:
  hibernate:
    dialect:
      MySQL8Dialect: